---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - cloudflareaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - cloudflareaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - cloudflareaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - dnsrecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - dnsrecords/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - dnsrecords/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - tunnelconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - tunnelconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - tunnelconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - tunnels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - tunnels/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - tunnels/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - workerscripts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - workerscripts/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - workerscripts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - zones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - zones/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - zones/status
  verbs:
  - get
  - patch
  - update
