---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - cloudflareaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - cloudflareaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare.cloudflare.k8s.io
  resources:
  - cloudflareaccounts/status
  verbs:
  - get
  - patch
  - update
