#!/usr/bin/env bash
# Regenerates the parts of the Helm chart that come from controller-gen
# output, so the chart can never drift from config/:
#   - helm/kflare/templates/crds/*.yaml  from config/crd/bases/*.yaml
#   - helm/kflare/files/manager-rules.yaml from the rules in config/rbac/role.yaml
# Run through `make helm`, which runs `make manifests` first.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHART="$ROOT/helm/kflare"

rm -f "$CHART"/templates/crds/*.yaml
for src in "$ROOT"/config/crd/bases/*.yaml; do
  if grep -q '{{' "$src"; then
    echo "error: $src contains '{{', which Helm would treat as a template" >&2
    exit 1
  fi
  dest="$CHART/templates/crds/$(basename "$src" | sed 's/^kflare\.dev_//')"
  {
    echo "# Generated by hack/sync-helm-chart.sh from config/crd/bases/$(basename "$src"). DO NOT EDIT."
    echo '{{- if .Values.crds.enabled }}'
    # Add the chart labels, and the keep policy so that uninstalling the
    # chart never deletes the CRDs (which would delete every kflare resource).
    awk '
      /^metadata:$/ && !done {
        print
        print "  labels:"
        print "    {{- include \"kflare.labels\" . | nindent 4 }}"
        next
      }
      /^  annotations:$/ && !done {
        print
        print "    {{- if .Values.crds.keep }}"
        print "    helm.sh/resource-policy: keep"
        print "    {{- end }}"
        done = 1
        next
      }
      { print }
    ' "$src" | sed '1{/^---$/d}'
    echo '{{- end }}'
  } > "$dest"
done

{
  echo "# Generated by hack/sync-helm-chart.sh from config/rbac/role.yaml. DO NOT EDIT."
  sed -n '/^rules:$/,$p' "$ROOT/config/rbac/role.yaml" | sed '1d'
} > "$CHART/files/manager-rules.yaml"
